- CHANGELOG.md
> update CHANGELOG v0.0.1

- .github/workflows/CI.yml
- fix packaged files
- removes Docker related files from workflow artifacts upload
- removes intended ignore files from release package
> fix packaged files

- Contents/Code/__init__.py
- Contents/Code/plex_api_helper.py
- fix plexhints import for docker
- Fixes #10
> fix plexhints import for docker

- .github/workflows/CI.yml
- fix release package (remove intended ignore files)
> fix release package

- CHANGELOG.md
> Update changelog for v0.0.2

- scripts/build_plist.py
- fix plist formatting
- use `fas` instead of `fa-solid` for font awesome
> fix plist formatting

- docs/source/about/usage.rst
- update usage instructions
- after further testing, it appears that it is not required to "fix match" on items
> update usage instructions

- CHANGELOG.md
- Contents/Code/__init__.py
- Contents/Code/plex_api_helper.py
- Contents/DefaultPrefs.json
- docs/source/about/usage.rst
- improve plexapi timeout
- changing timeout will no longer require a Plex Media Server restart
> improve plexapi timeout

- requirements-dev.txt
- lock python version for docs theme
> lock python version for docs theme

- Contents/Code/default_prefs.py
- Contents/Code/plex_api_helper.py
- Contents/DefaultPrefs.json
- docs/source/about/usage.rst
- autofetch plex-token
- Fixes #37
> autofetch plex-token

- CHANGELOG.md
- Update CHANGELOG.md v0.0.6
- Add release URLs to end of changelog
> Update CHANGELOG.md v0.0.6

- CHANGELOG.md
- README.rst
> fix readme status badge

- CHANGELOG.md
- README.rst
Fixes read the docs build for epub version. See [here](https://github.com/badges/shields/issues/8671#issuecomment-1369157186) for additional context.
> fix read the docs build

- .github/workflows/CI.yml
Update workflow concurrency in order to reduce runner usage.
> update workflow concurrency

- Contents/Code/__init__.py
- Contents/Code/helpers.py
- Contents/Code/plex_api_helper.py
- Contents/Code/youtube_dl_helper.py
- Contents/Libraries/Shared/requirements.txt
- README.rst
- docs/source/about/usage.rst
- docs/source/code_docs/youtube_dl_helper.rst
- docs/source/toc.rst
This PR adds support for the new Plex Movie agent. It works by monitoring the Plex server using the `plexapi.alert.AlertListener` (https://python-plexapi.readthedocs.io/en/latest/modules/alert.html#module-plexapi.alert), and handling requests accordingly.
> add support for new Plex Movie agent

- CHANGELOG.md
- update changelog for v0.1.0 release
> update changelog for v0.1.0

- Contents/Code/__init__.py
- Contents/Code/default_prefs.py
- Contents/Code/plex_api_helper.py
- Contents/DefaultPrefs.json
- Contents/Libraries/Shared/requirements.txt
- docs/source/about/usage.rst
Improve Plex Movie agent queue handling. Now uses `Queue` (known as `queue` in Python 3), and multithreading. Adds an option for the user to specify the number of threads to use for uploading theme songs.
> improve Plex Movie agent queue handling

- CHANGELOG.md
> Update CHANGELOG.md for v0.1.2

- Contents/Code/__init__.py
- Contents/Code/default_prefs.py
- Contents/Code/helpers.py
- Contents/Code/plex_api_helper.py
- Contents/DefaultPrefs.json
- docs/source/about/usage.rst
This PR improves error handling and logging when theme song does not exist in ThemerrDB. It also logs the url for where the user should go to have the item added.
Additionally, add a retry loop for uploading theme songs.
> improve error handling and logging

- CHANGELOG.md
> changelog: v0.1.3

- Dockerfile
Force system exit when docker build errors occur.
> docker: enforce system exit on build errors

- .dockerignore
- .github/workflows/python-tests.yml
- tests/conftest.py
- tests/unit/test_code.py
- tests/unit/test_youtube_dl_helper.py
> tests: add pytest

- requirements-dev.txt
Dependabot should have taken care of this but didn't.
build(deps): bump sphinx-rtd-theme from 1.1.1 to 1.2.0
> build(deps): bump sphinx-rtd-theme from 1.1.1 to 1.2.0

- Contents/Libraries/Shared/requirements.txt
Since `youtube-dl` is broken and no new release is being made available, this PR installs `youtube-dl` from git instead of PyPi.
:warning: It is unknown (and unlikely) that @dependabot will be able to keep this dependency updated.
> build(deps): install youtube-dl from git

- CHANGELOG.md
> docs(changelog): add v0.2.0

- .github/workflows/localize.yml
Fix `git diff` command in localization ci.
> ci(localization): fix git diff

- .github/workflows/localize.yml
> ci(localization): fix localization path

- .github/workflows/python-tests.yml
- requirements.txt
Install python dependencies to an alternate location in order to invoke pytest on any tests that are present.
> ci(tests): test python dependencies

- Contents/Code/webapp.py
- tests/functional/test_webapp.py
- Fix translation file names
- Rename `test_favicon` to `test_image` for consistency.
> fix(localization): fix translation file names

- .github/workflows/CI.yml
- .github/workflows/python-tests.yml
- Contents/Code/__init__.py
- Contents/Code/plex_api_helper.py
- requirements.txt
Move to new `python-plexapi-backport`.
> build(deps): use python-plexapi-backport

- .github/workflows/CI.yml
- requirements-dev.txt
- requirements.txt
Bump plexhints and python-plexapi-backport.
- Closes #197 
> build(deps): bump plexhints and plexapi-backport

- Contents/Code/plex_api_helper.py
> fix: use correct types for plex item typehints

- Contents/Resources/web/css/custom.css
Fix CSS selector
- [] I have commented my code, particularly in hard-to-understand areas
> fix: fix css

- Contents/Code/webapp.py
- Contents/Resources/web/templates/home.html
This PR fixes an issue where completed themes could inaccurately show as being provided by Themerr. There is now an additional detection where we check for the existence of the themerr json file. This is still not 100% foolproof, but it should be accurate except in very rare situations.
> fix(ui): correct issue where themerr-provided field may not be accurate

- Contents/Code/webapp.py
> fix: use item original title if present

- CHANGELOG.md
> docs: update v0.3.0 changelog

- Contents/Code/plex_api_helper.py
Remove unneeded globals and if logic.
> refactor(plexapi_api_helper): improve plex_server creation

- CHANGELOG.md
Add unreleased version to changelog, hopefully allowing CI to build on merged to nightly... thus providing coverage artifacts to codecov.
> docs(changelog): add unreleased version

- CHANGELOG.md
> docs(changelog): prepare v0.3.1

- CHANGELOG.md
Update docs for v0.3.1 release.
> docs(changelog): v0.3.1

- Contents/Code/webapp.py
Fixes issue url for items with no known ID.
- Fixes #254 
> fix(ui): modify action for collections with no known id

- tests/conftest.py
- tests/functional/test_plex_plugin.py
- tests/functional/test_webapp.py
- tests/unit/test_code.py
- tests/unit/test_general_helper.py
- tests/unit/test_lizardbyte_db_helper.py
- tests/unit/test_scheduled_tasks.py
- tests/unit/test_themerr_db_helper.py
- tests/unit/test_tmdb_helper.py
- tests/unit/test_youtube_dl_helper.py
General improvements to tests.
> test: improve tests

- .github/workflows/localize.yml
Recursively checkout submodules for localization workflow.
> ci(localization): checkout submodules

- docs/source/about/troubleshooting.rst
- docs/source/conf.py
- tests/ci/test_docs.py
- Remove comment about youtube credentials, since they are no longer possible to use inside of this plugin.
- Small code style change to `conf.py`
- Test build docs in a matrix.
> docs: misc updates

- Contents/Code/__init__.py
- Contents/Code/general_helper.py
- Contents/Code/migration_helper.py
- Contents/Code/plex_api_helper.py
- Contents/Code/scheduled_tasks.py
- Contents/Code/themerr_db_helper.py
- Contents/Code/webapp.py
- Contents/Code/youtube_dl_helper.py
- docs/source/conf.py
This PR adds the intersphinx extension to allow linking between other projects using sphinx docs.
> docs: add intersphinx extension

- requirements-dev.txt
- requirements.txt
> build(deps): bump plexapi-backport from 4.15.6 to 4.15.10

- Contents/Code/general_helper.py
- Contents/Code/youtube_dl_helper.py
- docs/source/code_docs/themerr_db_helper.rst
- docs/source/toc.rst
Some of the changes that were in https://github.com/LizardByte/Themerr-plex/pull/227
> style: various code style and docs adjustments

- Contents/Code/general_helper.py
- Contents/Code/webapp.py
The existing code could potentially crash the cache update thread.
> fix(ui): ensure finding theme provider doesn't crash thread

- Contents/Resources/web/templates/home.html
Fixes https://github.com/LizardByte/Themerr-plex/security/code-scanning/3
> fix(ui): add relationship to issue url hyperlink

- Contents/Code/webapp.py
- Contents/Resources/web/templates/home.html
"Movies" was displayed in the UI for the TV Show progress bar.
> fix(ui): use correct label in progress bar

- crowdin.yml
Files uploaded to repo from Crowdin, should not have any replacements in the file name.
> build(crowdin): fix file name replacement

- crowdin.yml
This PR renames strings on Crowdin from `en.json` to `themerr-plex.json`.
https://community.crowdin.com/t/questions-on-best-practices/7377/2
> build(i18n): rename source strings on crowdin

- crowdin.yml
Add `update_option` and update `dest` for json source.
> build(i18n): add crowdin update_option

- crowdin.yml
https://community.crowdin.com/t/questions-on-best-practices/7377/9?u=reenignearcher
> build(i18n): update dest options for crowdin config
