LizardByte/Themerr-plex

- Contents/Code/__init__.py
- Contents/Code/default_prefs.py
- Contents/Code/plex_api_helper.py
- Contents/DefaultPrefs.json
- docs/source/about/usage.rst
- fix plexapi default timeout
- set default timeout to 180 seconds (3 minutes)
> fix plexapi default timeout

- .github/workflows/CI.yml
- CHANGELOG.md
- Contents/Code/plex_api_helper.py
- docs/source/about/troubleshooting.rst
- docs/source/toc.rst
- fix `plexapi.utils` import which caused plugin to hang
> fix `plexapi.utils` import

- CHANGELOG.md
- Dockerfile
- Removes `--link` arg from final COPY step, which prevents the docker mod from loading the plugin properly.
- Update changelog for v0.1.4.
> docker: remove link arg from final copy

- .dockerignore
- Dockerfile
Also revert removing the `--link` arg.
Move to ubuntu base image for Docker build. Additionally, revert removing the `--link` arg. The issue with docker mods is tracked here: https://github.com/linuxserver/docker-mods/issues/575
> docker: move to ubuntu base image

- docs/source/contributing/testing.rst
Remove admonition from pytest section. Missed this in #101 .
> docs: remove pytest admonition

- Dockerfile
Use python 2.7.18 instead of 2.7.17. Not sure why @dependabot changed from `2.7-buster` to `2.7.17-buster`...
> build(deps): bump python from 2.7.17-buster to 2.7.18-buster

- Dockerfile
- docs/source/contributing/contributing.rst
- requirements.txt
Move docker image to Ubuntu 22.04.
> build(docker): move docker image to ubuntu 22.04

- .github/workflows/CI.yml
Remove `tests` directory from published artifacts/packages.
> build: exclude tests directory from package

- .github/workflows/CI.yml
- .github/workflows/python-tests.yml
Fix Python 2.7 setup using new org action -> https://github.com/LizardByte/.github/pull/237
This change is required due to GitHub removing support for Python 2.7 in runners -> https://github.com/actions/setup-python/issues/672
> fix(ci): fix python 2.7 setup

- Contents/Code/default_prefs.py
- Contents/Code/youtube_dl_helper.py
- Contents/DefaultPrefs.json
- docs/source/about/usage.rst
This PR adds a new preference to prefer MP4A AAC codec over Opus codec, which should improve compatibility with Apple devices.
- Fixes #121 
> fix(codec): improve compatibility with Apple devices

- .github/workflows/localize.yml
Install `requests`, so that `python-plexapi` will be happy.
> fix(ci): localization workflow fails to install python-plexapi

- .github/workflows/python-tests.yml
- .readthedocs.yaml
- CHANGELOG.md
- Contents/Code/__init__.py
- Contents/Code/constants.py
- Contents/Code/default_prefs.py
- Contents/Code/general_helper.py
- Contents/Code/lizardbyte_db_helper.py
- Contents/Code/plex_api_helper.py
- Contents/Code/scheduled_tasks.py
- Contents/Code/tmdb_helper.py
- Contents/Code/webapp.py
- Contents/DefaultPrefs.json
- Contents/Resources/web/templates/home.html
- docs/source/about/usage.rst
- docs/source/code_docs/general_helper.rst
- docs/source/code_docs/lizardbyte_db_helper.rst
- docs/source/code_docs/scheduled_tasks.rst
- docs/source/code_docs/tmdb_helper.rst
- docs/source/toc.rst
- requirements.txt
- scripts/build_plist.py
This PR adds support for adding themes to collection items in Plex. Since collections cannot have metadata agents, it does so by looping over every library with a scheduled task. The interval for the scheduled task is configurable.
Additionally, since we are looping over every library, this PR also adds the option to update themes for movies during the same update loop.
Themerr-plex now will also only update themes if required, i.e. the theme song that was previously used does not match the theme song listed in ThemerrDB.
Todo:
Check if Themerr-plex is enabled:
- `/system/agents/com.plexapp.agents.themoviedb/config/1`
- `/system/agents/com.plexapp.agents.imdb/config/1`
- `/system/agents/dev.lizardbyte.retroarcher-plex/config/1`
1 indicates Movie library, 2 indicates TV library... of …
> feat: add support for collections

- .readthedocs.yaml
- .rstcheck.cfg
- README.rst
- docs/source/about/installation.rst
- docs/source/about/troubleshooting.rst
- docs/source/about/usage.rst
- docs/source/contributing/build.rst
- docs/source/contributing/contributing.rst
- docs/source/contributing/database.rst
- docs/source/contributing/testing.rst
- requirements-dev.txt
Fix readthedocs build and enable rstcheck (lint)
> docs: fix readthedocs build

- .github/workflows/CI.yml
- .github/workflows/localize.yml
This PR moves to the new LizardByte setup python action.
> ci: use new LizardByte setup python action

- tests/functional/test_plex_plugin.py
Attempt to fix macOS failing to find plugin log file.
> test: fix macos functional test

- tests/functional/test_plex_plugin.py
Increase plugin log search timeout to 2 minutes.
> test: increase plugin log search timeout

- tests/conftest.py
- tests/functional/test_plex_plugin.py
Further improve tests, specifically waiting for the plugin to start due to delay on macOS.
> test: wait until plugin is ready

- .github/workflows/CI.yml
Use commit hash for setup python action, so that dependabot can (hopefully) pick up the changes.
> ci: use commit hash for setup python action

- Contents/Code/plex_api_helper.py
- on many Linux machines, `localhost` resolves to `::1`. The `websocket` module used here expects an `AF_INET` address, so it expectedly crashes when passed an IPv6 address such as `::1`. The default URL used for reaching Plex is modified to `127.0.0.1` to prevent this.
- Fixes #143
> Fix AlertListener on IPv6-aware hosts

- Contents/Code/plex_api_helper.py
> fix: Add error handling around update_plex_item to prevent hang

- Contents/Code/youtube_dl_helper.py
- tests/unit/test_youtube_dl_helper.py
- no code was present to handle YoutubeDL raising an exception. If such a case were to happen previously, the whole thread would crash; in practice this means that if any movie in the library can't be downloaded for any reason, the worker thread trying to download it will crash and stop processing any more content. In the worst case (e.g. mine) you can end up with all threads hung. Refreshing metadata or restarting the plugin doesn't change anything, the problem is logical and deterministic. Errors are now handled properly and printed to the plugin logs, and the process can continue.
- also, a typo in the YoutubeDL call is fixed (`outmpl` -> `outtmpl`)
- Fixes #163
must be …
> Add error handling and logging for Youtube-DL

- Contents/Code/constants.py
- Contents/Code/plex_api_helper.py
Before, the skip check was done in `add_media`, i.e. after the call to `process_youtube`. As a result, even for media for which Themerr had already downloaded a theme, Youtube-DL was still called to try and get the stream URL, which 
> fix: Move skip check before call to Youtube-DL

- Contents/Code/plex_api_helper.py
This disable auto-reloading of fields by PlexAPI. This feature is not needed by Themerr. If enabled, it performs a web request everytime a missing field is accessed. On my machine, the webUI takes more than 10 min to load with autoreload, and less than a second without.
> fix: disable auto-reload since it is not needed and only harms perf

- .github/workflows/CI.yml
- Dockerfile
- patches/youtube_dl-compat.patch
- patches/youtube_dl-extractor.patch
- requirements.txt
> build(deps): bump youtube-dl

- Contents/Resources/web/templates/home.html
There is an issue where the progress bar will not fill to the max, due to an offset of 1.
> fix(ui): progress bar will now fill to max

- Contents/Code/themerr_db_helper.py
- tests/conftest.py
- tests/unit/test_themerr_db_helper.py
There is a potential for the database_cache to be updated in parallel.
I'm not 100% sure the cause of this error, but using a lock should be more reliable.
```txt
2023-11-12 22:22:38,763 (1cb0) :  CRITICAL (core:574) - JSON encoding error (most recent call last):
File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-8f4248874\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\data.py", line 187, in to_string
return simplejson.dumps(obj)
File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Python\lib\python2.7\site-packages\simplejson\__init__.py", line 354, in dumps
return _default_encoder.encode(obj)
File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Python\lib\python2.7\site-packages\simplejson\encoder.py", line 264, in encode …
```
> fix: correct issue where database_cache may be updated in parallel

- Contents/Code/webapp.py
Some items would not properly show "edit" when they were provided by ThemerrDB. This was due to not being able to detect if the item exists in ThemerrDB after the logic was changed in #209.
> fix(ui): use correct action button for themerr provided items

- Contents/Code/default_prefs.py
- Contents/Code/scheduled_tasks.py
- Contents/Code/webapp.py
- Contents/DefaultPrefs.json
- Contents/Resources/web/templates/home_db_not_cached.html
- docs/source/about/usage.rst
- tests/unit/test_webapp.py
The data required for the web UI has been slow to load in some cases (using IMDB or IGDB databases). This PR adds the ability to cache the data to improve loading times. The first time the UI is accessed, this will still be slow, but once the data has been cached, it will be nearly instant.
The cache is saved to a file, so that it's available between Plex server restarts.
> fix(ui): improve speed of dashboard by caching data

- Contents/Code/constants.py
- Contents/Code/plex_api_helper.py
Locked fields will not be updated by Themerr. Fields updated by Themerr will be marked as non-locked.
> fix: don't update locked fields + unlock fields after update

- Contents/Code/__init__.py
> fix: disable Plex plugin framework sandbox and add back all missing builtins

- Contents/Code/plex_api_helper.py
There are random bugs with importing `_strptime` in plexapi... detected in CI tests.
```txt
2023-12-02 02:14:30,926 (7fd1a97dbb38) :  CRITICAL (plex_api_helper:551) - Unexpected error processing rating key: 2, error: Failed to import _strptime because the import lockis held by another thread. (most recent call last):
File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Themerr-plex.bundle/Contents/Code/plex_api_helper.py", line 549, in process_queue
update_plex_item(rating_key=rating_key)  # process that rating_key
File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Themerr-plex.bundle/Contents/Code/plex_api_helper.py", line 115, in update_plex_item
item = get_plex_item(rating_key=rating_key)
File …
```
> fix(plexapi): fix random _strptime import errors

- Contents/Code/__init__.py
- Contents/Code/default_prefs.py
- Contents/Code/migration_helper.py
- Contents/Code/plex_api_helper.py
- Contents/DefaultPrefs.json
- docs/source/about/usage.rst
- docs/source/code_docs/migration_helper.rst
- docs/source/toc.rst
- tests/unit/test_migration_helper.py
- tests/unit/test_plex_api_helper.py
Add a method to migrate from previous versions. A use case for this is when upgrading from v0.2 to v0.3.0, themes previously added by Themerr will not be known to be added by Themerr... and they are also locked so those themes will never be updated.
> feat: migrate from previous versions

- Contents/Code/webapp.py
- Contents/Resources/web/templates/home.html
This PR fixes an issue where libraries with spaces in the name could not collapse in the WebUI. Users will need to wait until the database cache refreshes before the collapse/expand buttons will work properly.
- Fixes #255 
> fix(ui): fix collapse issue with libraries that contain spaces in the name

- Contents/Code/webapp.py
- tests/functional/test_webapp.py
Return the correct template when the database cache file does not exist yet.
> fix(ui): return correct templates

- Contents/Code/webapp.py
- requirements.txt
Some item titles may not be properly quoted in the issue URL. This PR implements url quoting around the item title. I opted to use `quote_plus` from `six` to make it more similar to Python 3, which most developers are more familiar with at this point in time.
- Fixes #328 
> fix(ui): url encode item titles in issue url

- Contents/Code/webapp.py
In some cases, the IMDB id is used for the issue URL instead of the TMDB. ThemerrDB only accepts TMDB ids, so this PR nullifies issue URLs for items where the TMDB cannot be determined.
- Fixes #328 
> fix(ui): ensure issue urls use tmdb id

- Contents/Code/constants.py
- Contents/Code/general_helper.py
- Contents/Code/plex_api_helper.py
- tests/unit/test_general_helper.py
Plex runs the Themerr agent even if it is disabled in the agent menu. Due to how we add theme songs using the API (instead of the plugin framework), we need to perform a check to see if we should add the theme or not.
> fix(legacy agents): do not upload themes unless Themerr is enabled

- Contents/Code/webapp.py
The dashboard could fail to cache if a local item with no database id was present in any section.
> fix(dashboard): fix issue where local items could prevent ui cache from completing

- Contents/Code/default_prefs.py
- Contents/Code/migration_helper.py
- Contents/DefaultPrefs.json
- docs/source/about/usage.rst
- tests/unit/test_migration_helper.py
This PR adds a migration option to unlock fields locked for collections prior to v0.3.0. It only unlocks fields for collections with a theme song.
> fix(collections): add migration for collection metadata

- Contents/Code/default_prefs.py
- Contents/Code/plex_api_helper.py
- Contents/DefaultPrefs.json
- docs/source/about/usage.rst
This PR adds an option to completely ignore locked fields when adding themes or collection metadata.
> feat: add option to ignore locked fields

- .github/workflows/CI.yml
- Contents/Code/__init__.py
- Contents/Code/constants.py
- Contents/Code/default_prefs.py
- Contents/Code/general_helper.py
- Contents/Code/plex_api_helper.py
- Contents/Code/themerr_db_helper.py
- Contents/Code/tmdb_helper.py
- Contents/Code/webapp.py
- Contents/DefaultPrefs.json
- Contents/Resources/web/templates/home.html
- README.rst
- docs/source/about/usage.rst
- tests/conftest.py
- tests/functional/test_plex_plugin.py
- tests/unit/test_code.py
- tests/unit/test_general_helper.py
- tests/unit/test_migration_helper.py
- tests/unit/test_plex_api_helper.py
- tests/unit/test_themerr_db_helper.py
- tests/unit/test_tmdb_helper.py
This PR adds support for TV themes. The user must enable Themerr in the agent priority list for themes to be provided. Themerr should skip items that have a theme provided by Plex, by default.
- Improved theme provider detection
- Plexhints updated with support for tv libraries, and support for different types of query requests during Plex bootstrapping step
- `PlexPartialObject` used as typehint in more places
- `get_tmdb_id_from_imdb_id` changed to `get_tmdb_id_from_external_id` in order to support imdb and tvdb
- `user_provided` and `themerr_provided` properties in the web ui are replaced with `theme_provider`
[Allow …
> feat(shows): add support for tv shows

- Contents/Code/scheduled_tasks.py
When `bool_auto_update_items` was disabled, it would prevent the UI cache from being scheduled.
> fix(tasks): ensure ui can be cached if auto update items is disabled

- Contents/Code/plex_api_helper.py
- Contents/Code/tmdb_helper.py
> fix(collections): use library language in tmdb query

- codecov.yml
Only notify of coverage after all builds are complete. This will be better for automerge cases.
> ci(codecov): notify after all builds complete
